from __future__ import annotations

import unicodedata
from typing import Any


MACHINE_DEPENDENT_TEXT_REPLACEMENTS: dict[str, str] = {
    "№": "No.",
    "㎝": "cm",
    "㎜": "mm",
    "㎏": "kg",
    "㎡": "m2",
    "Ⅱ": "II",
    "É": "E",
    "㈱": "株式会社",
    "①": "1",
    "②": "2",
    "③": "3",
    "④": "4",
    "⑤": "5",
    "⑥": "6",
    "⑦": "7",
    "⑧": "8",
    "⑨": "9",
    "⑩": "10",
}

# RMS genre dictionaries compare these names literally.  Keep aliases here so
# a payload generated by an older sanitizer can still be retried safely.
RAKUTEN_ATTRIBUTE_NAME_ALIASES: dict[str, str] = {
    "原産国/製造国": "原産国／製造国",
}


def canonical_rakuten_attribute_name(value: object) -> str:
    name = str(value or "").strip()
    return RAKUTEN_ATTRIBUTE_NAME_ALIASES.get(name, name)


def sanitize_text_for_rakuten_api(value: str) -> str:
    sanitized = str(value)
    for source, replacement in MACHINE_DEPENDENT_TEXT_REPLACEMENTS.items():
        sanitized = sanitized.replace(source, replacement)
    # RMS rejects a broader set of compatibility characters than ordinary
    # Windows CP932 encoding does.  NFKC converts the remaining safe forms
    # (for example full-width Latin letters and enclosed units) to plain text.
    sanitized = unicodedata.normalize("NFKC", sanitized)
    return "".join(_strip_latin_diacritic(character) for character in sanitized)


def _strip_latin_diacritic(character: str) -> str:
    """Convert accented Latin letters such as É without touching Japanese."""
    codepoint = ord(character)
    if not (0x00C0 <= codepoint <= 0x024F):
        return character
    ascii_value = unicodedata.normalize("NFKD", character).encode("ascii", "ignore").decode("ascii")
    return ascii_value or character


def sanitize_payload_text_for_rakuten_api(value: Any) -> Any:
    if isinstance(value, str):
        return sanitize_text_for_rakuten_api(value)
    if isinstance(value, list):
        return [sanitize_payload_text_for_rakuten_api(item) for item in value]
    if isinstance(value, dict):
        # RMS resolves variant attribute names against its genre dictionary by
        # an exact string match.  Normalizing all strings would turn a valid
        # name such as ``原産国／製造国`` into ``原産国/製造国`` and make the
        # Item API reject the entire payload.  Keep the structural attribute
        # name intact; its values (and all normal product text) are still
        # sanitized for machine-dependent characters.
        is_attribute = "name" in value and ("values" in value or "value" in value)
        return {
            key: (canonical_rakuten_attribute_name(item) if is_attribute and key == "name" else sanitize_payload_text_for_rakuten_api(item))
            for key, item in value.items()
        }
    return value
